### ISSUE TITLE
CMakeLists.txt not recognized & no comments

### ISSUE THREAD

**Issue by maziac** [uctakeoff/vscode-counter#105]
Hi,

I found that the CMakeLists.txt files are not recognized/found by VSCodeCounter.
Investigating this I found that VSCodeCounter looks for "CMakelists.txt" instead of "CMakeLists.txt".
I.e. the "l" is lowercase, it should be uppercase.
Even on Windows it is not working.

I changed it for myself, then CMakeLists.txt files are found correctly.

But there is a 2nd problem:
Commented lines are not recognized in CMakeLists.txt.

Sorry, that I put two errors in one issue, but the 2nd problem cannot be seen if the first is not solved.

**Comment by uctakeoff** [comment]
@maziac 
VSCodeCounter itself does not have the ability to determine the contents of a file. So CMakeLists.txt is not recognized because it does not contain a language extension that can recognize it, and l is recognized in lowercase because it contains a language extension that recognizes l as a lowercase letter, so it is not a problem with VSCodeCounter itself.

**Comment by uctakeoff** [comment]
@maziac 
I fixed it in v3.6.1. Please try it.

**Comment by maziac** [comment]
CMakeLists.txt files are recognized now, thank you.
(The commented lines are still not recognized, but I think that was anyhow not fixed.
If it is not inside vscode-counter what else is responsible for this?)
